baseURL = "https://ashy-rock-0d65ef90f.4.azurestaticapps.net/"
languageCode = "en-us"
title = "Rainaldi.dev"
theme = "tophat"
paginate = 5

[params]
    
  subtitle = "Your blog subtitle"
  description = "Your blog description"
  author = "Lou Rainaldi"

  main = "pages"
  featured = true
  
  # You can customize the visibility of some elements like date, reading time, words counter and tags inside article by setting true or false
  show_date_on_article = true
  show_reading_time_on_article = true
  show_words_count_on_article = true
  show_tags_on_article = true 

  [menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/pages/about/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/pages/contact/"    

  [[menu.social]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/ljrain"
